version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: N1234n
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: necip
            MYSQL_PASSWORD: Necip_1903
        networks:
            - necipnet
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - necipnet
networks:
    necipnet:
        driver: bridge

