github-token = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"

github-name = "XXXXXXXXXXXXXXXXXXXXXXXXXX"

server-name = "XXXXXXXXXXXXXXXXXXXXXXXXXX"

key_name = "XXXXXXXXXXXXXXXXXXXXXXXXXX"

hosted-zone = "XXXXXXXXXXXXXXXXXXXXXXXXXX"